--DBA 
--CREAR ROLE DBA
CREATE ROLE dba WITH SUPERUSER;

GRANT USAGE ON SCHEMA CLINICA TO dba;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CLINICA TO dba WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA TO dba WITH GRANT OPTION; 

CREATE USER administrador WITH PASSWORD '12345' IN ROLE dba;


DROP USER administrador;

REVOKE  ALL PRIVILEGES ON ALL TABLES IN SCHEMA CLINICA FROM dba;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA FROM dba; 

REVOKE USAGE ON SCHEMA CLINICA FROM dba;

DROP ROLE dba;

--JEFE_ESPECIALISTA
--CREAR ROLE DE JEFE_ESPECIALISTA
CREATE ROLE jefe_especialista;

GRANT USAGE ON SCHEMA CLINICA TO jefe_especialista;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA TO jefe_especialista WITH GRANT OPTION; 

GRANT SELECT, INSERT, UPDATE 
ON CLINICA.EXPEDIENTE, CLINICA.EXPEDIENTE_DIAGNOSTICO, CLINICA.ESPECIALISTA
TO jefe_especialista WITH GRANT OPTION;

GRANT DELETE ON CLINICA.ESPECIALISTA 
TO jefe_especialista WITH GRANT OPTION;

CREATE USER jefe_especialista_1 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE jefe_especialista;


DROP ROLE jefe_especialista;

REVOKE USAGE ON SCHEMA CLINICA FROM jefe_especialista;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA FROM dba; 

REVOKE INSERT, SELECT, UPDATE ON CLINICA.EXPEDIENTE, CLINICA.EXPEDIENTE_DIAGNOSTICO, CLINICA.ESPECIALISTA
FROM jefe_especialista;

REVOKE DELETE ON CLINICA.ESPECIALISTA
FROM jefe_especialista;

DROP USER jefe_especialista_1;

--ESPECIALISTA
--CREAR ROLE DE ESPECIALISTA
CREATE ROLE especialista;

GRANT USAGE ON SCHEMA CLINICA TO especialista;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA TO especialista WITH GRANT OPTION; 

GRANT SELECT, INSERT, UPDATE 
ON CLINICA.EXPEDIENTE, CLINICA.EXPEDIENTE_DIAGNOSTICO
TO especialista WITH GRANT OPTION;

CREATE USER especialista_1 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE especialista;
CREATE USER especialista_2 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE especialista;
CREATE USER especialista_3 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE especialista;


DROP ROLE especialista;

REVOKE USAGE ON SCHEMA CLINICA FROM especialista;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA FROM especialista; 

REVOKE SELECT, INSERT, UPDATE ON CLINICA.EXPEDIENTE, CLINICA.EXPEDIENTE_DIAGNOSTICO
FROM especialista;

DROP USER especialista_1;
DROP USER especialista_2;
DROP USER especialista_3;


--RECEPCIONISTA
--CREAR ROLE DE RECEPCIONISTA
CREATE ROLE recepcionista;

GRANT USAGE ON SCHEMA CLINICA TO recepcionista;

GRANT SELECT, INSERT, UPDATE 
ON CLINICA.PACIENTE, CLINICA.CITA, CLINICA.AGENDAR_CITA
TO recepcionista WITH GRANT OPTION;

GRANT DELETE ON CLINICA.PACIENTE TO recepcionista WITH GRANT OPTION;

GRANT INSERT ON CLINICA.DATOS_PACIENTES_PERSONAL TO recepcionista WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA TO recepcionista WITH GRANT OPTION;

CREATE USER recepcionista_1 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE recepcionista;
CREATE USER recepcionista_2 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE recepcionista;
CREATE USER recepcionista_3 WITH PASSWORD '12345' CONNECTION LIMIT 1 IN ROLE recepcionista;


DROP ROLE recepcionista;

REVOKE USAGE ON SCHEMA CLINICA FROM recepcionista;

REVOKE SELECT, INSERT, UPDATE ON CLINICA.PACIENTE, CLINICA.CITA, CLINICA.AGENDAR_CITA
FROM recepcionista;

REVOKE DELETE ON CLINICA.PACIENTE FROM recepcionista;

REVOKE INSERT ON CLINICA.DATOS_PACIENTES_PERSONAL FROM recepcionista;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CLINICA FROM recepcionista;

DROP USER recepcionista_1;
DROP USER recepcionista_2;
DROP USER recepcionista_3;




